theme: jekyll-theme-minimal
author: Duarte Castelo Grande de Carvalho (dcgc)
title: dcgc
email: geral@dcgc.io
github_username:  dcgc
gitlab_username:  dcgc
timezone: 'Europe/Warsaw'
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
  - 
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
disqus:
  shortname: duartecastelograndedecarvalho
